import { Prisma } from "../../generated/prisma/client.js";
import type { Db } from "../../core/db.js";
import type { ShortUrlRepository } from "./url.repository.js";
import { ShortCodeCollisionError, ShortUrlNotFoundError } from "./url.errors.js";

function isKnownPrismaError(error: unknown, code: string): error is Prisma.PrismaClientKnownRequestError {
  return error instanceof Prisma.PrismaClientKnownRequestError && error.code === code;
}

/** The only URL-module file that directly accesses Prisma's UrlShortUrl model. */
export function createPrismaShortUrlRepository(db: Db): ShortUrlRepository {
  return {
    async create(data) {
      try {
        return await db.urlShortUrl.create({ data });
      } catch (error) {
        // shortCode is the only caller-supplied unique field. UUID ids are
        // generated by Prisma, so P2002 here is a retryable code race.
        if (isKnownPrismaError(error, "P2002")) throw new ShortCodeCollisionError();
        throw error;
      }
    },
    async existsByCode(shortCode) {
      const record = await db.urlShortUrl.findUnique({ where: { shortCode }, select: { id: true } });
      return record !== null;
    },
    findByCode: (shortCode) => db.urlShortUrl.findUnique({ where: { shortCode } }),
    findOwnedByCode: (shortCode, userId) => db.urlShortUrl.findFirst({ where: { shortCode, userId } }),
    async deleteOwnedByCode(shortCode, userId) {
      const result = await db.urlShortUrl.deleteMany({ where: { shortCode, userId } });
      return result.count === 1;
    },
    async incrementClickCount(shortCode) {
      try {
        return await db.urlShortUrl.update({
          where: { shortCode },
          data: { clickCount: { increment: 1 } },
        });
      } catch (error) {
        if (isKnownPrismaError(error, "P2025")) throw new ShortUrlNotFoundError();
        throw error;
      }
    },
  };
}
